# Project information
site_name: "نوا تیچ"
site_description: "مستندات رسمی دستیار معلم"
# site_author: "Mohammadreza Berneti"
# site_url: "http://berneti.ir"

# Repository
repo_name: "ehs22n/school-AI"
repo_url: "https://github.com/ehs22n/school-AI"

# Copyright
copyright: "© 2025-2026"

# Directories
docs_dir: "pages"
site_dir: "docs"

# Navigation
nav:
  - مقدمه: index.md
  - بخش فنی: services.md
  - قوانین: rules.md
  - موجودیت ها و امکانات پروژه: entities_features.md

     

# Theme configuration
theme:
  name: material
  language: fa  # Enables Persian translations and RTL layout
  direction: rtl  # Right-to-left text direction
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - content.action.edit
    - toc.integrate
  palette:
    # Light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: حالت تاریک
    # Dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: حالت روشن
  font:
    text: "Vazirmatn"
    code: "Fira Code"
  icon:
    repo: fontawesome/brands/github

# Custom CSS
extra_css:
  - "theme/custom-docs.css"

# Extra options
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ehs22n
      name: GitHub
  generator: false

# Markdown extensions
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.details
  - toc:
      permalink: ⚓
  - pymdownx.superfences
  - attr_list
  - footnotes

# Plugins (optional but recommended)
plugins:
  - search:
      separator: '[\s\-]+'
      lang: ['fa', 'en']
